/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        "sanctum.csrf-cookie": [],
        "filepond-process": [],
        "filepond-patch": [],
        "filepond-head": [],
        "filepond-revert": [],
        "dashboard": [],
        "project.index": [],
        "project.show": [
            {
                "name": "id",
                "required": true
            }
        ],
        "project.update": [
            {
                "name": "id",
                "required": true
            }
        ],
        "project.store": [
            {
                "name": "id",
                "required": true
            }
        ],
        "project.delete": [
            {
                "name": "id",
                "required": true
            }
        ],
        "contractor.index": [],
        "contractor.show": [
            {
                "name": "id",
                "required": true
            }
        ],
        "contractor.update": [
            {
                "name": "id",
                "required": true
            }
        ],
        "contractor.store": [
            {
                "name": "id",
                "required": true
            }
        ],
        "contractor.delete": [
            {
                "name": "id",
                "required": true
            }
        ],
        "team.index": [],
        "team.update": [
            {
                "name": "id",
                "required": true
            }
        ],
        "team.delete": [
            {
                "name": "id",
                "required": true
            }
        ],
        "file.update": [
            {
                "name": "id",
                "required": true
            }
        ],
        "file.store": [
            {
                "name": "id",
                "required": true
            }
        ],
        "file.delete": [
            {
                "name": "id",
                "required": true
            }
        ],
        "milestone.update": [
            {
                "name": "id",
                "required": true
            }
        ],
        "milestone.store": [
            {
                "name": "id",
                "required": true
            }
        ],
        "milestone.delete": [
            {
                "name": "id",
                "required": true
            }
        ],
        "register": [],
        "login": [],
        "password.request": [],
        "password.email": [],
        "password.reset": [
            {
                "name": "token",
                "required": true
            }
        ],
        "password.store": [],
        "verification.notice": [],
        "verification.verify": [
            {
                "name": "id",
                "required": true
            },
            {
                "name": "hash",
                "required": true
            }
        ],
        "verification.send": [],
        "password.confirm": [],
        "password.update": [],
        "logout": []
    }
}
export { };
