/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "filepond-process": [],
    "filepond-patch": [],
    "filepond-head": [],
    "filepond-revert": [],
    "dashboard": [],
    "project.index": [],
    "project.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "project.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "project.store": [],
    "project.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "contractor.index": [],
    "contractor.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "contractor.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "contractor.store": [],
    "contractor.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "team.index": [],
    "team.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "team.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "project.details": [
        {
            "name": "id",
            "required": true
        }
    ],
    "project.milestones": [
        {
            "name": "id",
            "required": true
        }
    ],
    "project.files": [
        {
            "name": "id",
            "required": true
        }
    ],
    "project.status.change": [
        {
            "name": "id",
            "required": true
        }
    ],
    "file.store": [],
    "file.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "files.delete": [],
    "folder.update": [],
    "folder.store": [],
    "folder.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "milestone.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "milestone.store": [],
    "milestone.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
