/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "filepond-process": [],
    "filepond-patch": [],
    "filepond-head": [],
    "filepond-revert": [],
    "dashboard": [],
    "profile.update": [],
    "profile.delete": [],
    "avatar.update": [],
    "guest.projects": [],
    "projects.delete": [],
    "guest.project.show": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project.store": [],
    "project.delete": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project.details": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project.milestones": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project.files": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project.status.change": [],
    "project.assigned.update": [
        {
            "name": "project",
            "required": true
        }
    ],
    "contractor.index": [],
    "contractor.show": [
        {
            "name": "contractor",
            "required": true,
            "binding": "id"
        }
    ],
    "contractor.update": [
        {
            "name": "contractor",
            "required": true,
            "binding": "id"
        }
    ],
    "contractor.store": [],
    "contractor.delete": [
        {
            "name": "contractor",
            "required": true,
            "binding": "id"
        }
    ],
    "contractor.api": [],
    "team.index": [],
    "team.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "team.delete": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "team.api": [],
    "file.store": [],
    "file.delete": [
        {
            "name": "file",
            "required": true
        }
    ],
    "files.delete": [],
    "folder.update": [],
    "folder.store": [],
    "folder.delete": [
        {
            "name": "folder",
            "required": true,
            "binding": "id"
        }
    ],
    "milestone.update": [
        {
            "name": "milestone",
            "required": true,
            "binding": "id"
        }
    ],
    "milestone.store": [],
    "milestone.delete": [
        {
            "name": "milestone",
            "required": true,
            "binding": "id"
        }
    ],
    "setting.index": [],
    "setting.general.show": [],
    "setting.general.store": [],
    "setting.website.show": [],
    "setting.website.store": [],
    "role.index": [],
    "role.store": [],
    "role.delete": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "role.permission.show": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "home": [],
    "about": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "register": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
